name: consent-code

services:
  backend:
    build: Backend/
    image: backend-app:1.0
    container_name: backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=project_registry;Username=postgres;Password=root
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: project_registry
      POSTGRES_INITDB_ARGS: "-c datestyle='German, DMY'"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql

  vite-app:
    build: 
      context: ./frontend/CodeSoglasiyaFrontend
    image: frontend-app:1.0
    container_name: frontend
    ports: 
      - "5173:5173"
    volumes:
      - ./frontend/CodeSoglasiyaFrontend:/app
      - /app/node_modules

volumes:
  postgres_data:
