// <auto-generated />
using System;
using ConsentCode.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsentCode.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240929124834_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsentCode.Models.ProjectGeneralInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Monitoring")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Priority")
                        .HasColumnType("float4");

                    b.Property<string>("Program")
                        .HasColumnType("text");

                    b.Property<string>("RGT")
                        .HasColumnType("char");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrategyBelonging")
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectsGeneralInfo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7eadf4f-e161-42fe-9db6-9f906432025f"),
                            Code = "COC1",
                            Name = "Web App",
                            Priority = 7f,
                            Stage = "In Progress",
                            Status = "Archived",
                            Year = "24"
                        },
                        new
                        {
                            Id = new Guid("15a84b93-e3a6-4bd0-9130-e9cddfe42328"),
                            Code = "preCOC",
                            Name = "Game",
                            Priority = 3f,
                            Stage = "Done",
                            Status = "Archived",
                            Year = "23"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
