// <auto-generated />
using System;
using ConsentCode.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsentCode.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsentCode.Models.ProjectGeneralInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Priority")
                        .HasColumnType("real");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectsGeneralInfo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5ca0a66-3408-490d-af33-b8fdfff280f7"),
                            Code = "COC1",
                            Name = "Web App",
                            Priority = 7f,
                            Stage = "In Progress",
                            Status = "Archived",
                            Year = "24"
                        },
                        new
                        {
                            Id = new Guid("36305a06-e9fd-43a5-bc25-30d7f334769b"),
                            Code = "preCOC",
                            Name = "Game",
                            Priority = 3f,
                            Stage = "Done",
                            Status = "Archived",
                            Year = "23"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
