// <auto-generated />
using System;
using Backend.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.ProjectCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Budget")
                        .HasColumnType("integer");

                    b.Property<int?>("Contents")
                        .HasColumnType("integer");

                    b.Property<int?>("Deadlines")
                        .HasColumnType("integer");

                    b.Property<int?>("Goals")
                        .HasColumnType("integer");

                    b.Property<int?>("Progress")
                        .HasColumnType("integer");

                    b.Property<string>("ReportLink")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectsCondition");
                });

            modelBuilder.Entity("Backend.Models.ProjectGeneralInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Monitoring")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("Priority")
                        .HasColumnType("float4");

                    b.Property<string>("Program")
                        .HasColumnType("text");

                    b.Property<string>("RGT")
                        .HasColumnType("char");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrategyBelonging")
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectsGeneralInfo");
                });

            modelBuilder.Entity("Backend.Models.ProjectGoals", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AchieveCriteria")
                        .HasColumnType("text");

                    b.Property<string>("BusinessGoals")
                        .HasColumnType("text");

                    b.Property<string>("BusinessGoalsStatus")
                        .HasColumnType("text");

                    b.Property<string>("GoalsStatus")
                        .HasColumnType("text");

                    b.Property<string>("ImplCriteria")
                        .HasColumnType("text");

                    b.Property<string>("Product")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectsGoals");
                });

            modelBuilder.Entity("Backend.Models.ProjectTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ADM")
                        .HasColumnType("text");

                    b.Property<string>("BusinessAnalyst")
                        .HasColumnType("text");

                    b.Property<string>("BusinessLines")
                        .HasColumnType("text");

                    b.Property<string>("Customer")
                        .HasColumnType("text");

                    b.Property<string>("ExternalPeople")
                        .HasColumnType("text");

                    b.Property<string>("FRC")
                        .HasColumnType("text");

                    b.Property<string>("MCPeople")
                        .HasColumnType("text");

                    b.Property<string>("Manager")
                        .HasColumnType("text");

                    b.Property<string>("ProductOwner")
                        .HasColumnType("text");

                    b.Property<string>("Stakeholders")
                        .HasColumnType("text");

                    b.Property<string>("TeamLead")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectsTeam");
                });

            modelBuilder.Entity("Backend.Models.Views.ProjectConditionView", b =>
                {
                    b.Property<int?>("Budget")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Contents")
                        .HasColumnType("integer");

                    b.Property<int?>("Deadlines")
                        .HasColumnType("integer");

                    b.Property<int?>("Goals")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Progress")
                        .HasColumnType("integer");

                    b.Property<string>("ReportLink")
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("ProjectsConditionView", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Views.ProjectGoalsView", b =>
                {
                    b.Property<string>("AchieveCriteria")
                        .HasColumnType("text");

                    b.Property<string>("BusinessGoals")
                        .HasColumnType("text");

                    b.Property<string>("BusinessGoalsStatus")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoalsStatus")
                        .HasColumnType("text");

                    b.Property<string>("ImplCriteria")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Product")
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("ProjectsGoalsView", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Views.ProjectTeamView", b =>
                {
                    b.Property<string>("BusinessAnalyst")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Customer")
                        .HasColumnType("text");

                    b.Property<string>("MCPeople")
                        .HasColumnType("text");

                    b.Property<string>("Manager")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamLead")
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("ProjectsTeamView", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ProjectCondition", b =>
                {
                    b.HasOne("Backend.Models.ProjectGeneralInfo", "GeneralInfo")
                        .WithOne("Condition")
                        .HasForeignKey("Backend.Models.ProjectCondition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralInfo");
                });

            modelBuilder.Entity("Backend.Models.ProjectGoals", b =>
                {
                    b.HasOne("Backend.Models.ProjectGeneralInfo", "GeneralInfo")
                        .WithOne("Goals")
                        .HasForeignKey("Backend.Models.ProjectGoals", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralInfo");
                });

            modelBuilder.Entity("Backend.Models.ProjectTeam", b =>
                {
                    b.HasOne("Backend.Models.ProjectGeneralInfo", "GeneralInfo")
                        .WithOne("Team")
                        .HasForeignKey("Backend.Models.ProjectTeam", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralInfo");
                });

            modelBuilder.Entity("Backend.Models.ProjectGeneralInfo", b =>
                {
                    b.Navigation("Condition");

                    b.Navigation("Goals");

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
